### ISSUE TITLE
Segfault when hiding widgets using the vulkan renderer

### ISSUE THREAD

**Issue by FireBurn** [zaps166/QMPlay2#681]
This happens with both QMPlay2 23.10.22 and from the current git, I'm not sure if it's a bug in mesa (I'm running from git) - I'll open a bug with them too

Hiding or showing Information (I think so it resizes the video playing)

Everything works fine with the OpenGL renderer

GDB shows:

```
Thread 1 "QMPlay2" received signal SIGSEGV, Segmentation fault.
wsi_wl_swapchain_chain_free (chain=0x555555d9a320, pAllocator=0x555556565558) at ../mesa-9999/src/vulkan/wsi/wsi_common_wayland.c:2229
warning: 2229   ../mesa-9999/src/vulkan/wsi/wsi_common_wayland.c: No such file or directory
(gdb) bt
#0  wsi_wl_swapchain_chain_free (chain=0x555555d9a320, pAllocator=0x555556565558) at ../mesa-9999/src/vulkan/wsi/wsi_common_wayland.c:2229
#1  0x00007fffcd441285 in wsi_wl_swapchain_destroy (wsi_chain=0x555555d9a320, pAllocator=0x555556565558) at ../mesa-9999/src/vulkan/wsi/wsi_common_wayland.c:2275
#2  0x00007fffcd43052e in wsi_DestroySwapchainKHR (_device=0x555556565510, _swapchain=0x555555d9a320, pAllocator=0x0) at ../mesa-9999/src/vulkan/wsi/wsi_common.c:1042
#3  0x00007ffff7d06c18 in vk::Device::destroy<vk::DispatchLoaderDynamic> (d=..., allocator=..., swapchain=..., this=0x555556472468)
    at /var/tmp/portage/media-video/qmplay2-9999/work/qmplay2-9999/src/qmplay2/vulkan/headers/include/vulkan/vulkan_funcs.hpp:8662
#4  vk::ObjectDestroy<vk::Device, vk::DispatchLoaderDynamic>::destroy<vk::SwapchainKHR> (this=0x555556472468, t=...) at /var/tmp/portage/media-video/qmplay2-9999/work/qmplay2-9999/src/qmplay2/vulkan/headers/include/vulkan/vulkan.hpp:5968
#5  0x00007ffff7d06630 in vk::UniqueHandle<vk::SwapchainKHR, vk::DispatchLoaderDynamic>::reset (this=0x555556472468, value=...) at /var/tmp/portage/media-video/qmplay2-9999/work/qmplay2-9999/src/qmplay2/vulkan/headers/include/vulkan/vulkan.hpp:965
#6  0x00007ffff7cfeec7 in QmVk::SwapChain::init (this=0x555556472430, createInfo=...) at /var/tmp/portage/media-video/qmplay2-9999/work/qmplay2-9999/src/qmvk/SwapChain.cpp:138
#7  0x00007ffff7cfafb9 in QmVk::SwapChain::create (createInfo=...) at /var/tmp/portage/media-video/qmplay2-9999/work/qmplay2-9999/src/qmvk/SwapChain.cpp:44
#8  0x00007ffff7dbe4d9 in QmVk::Window::ensureSwapChain (this=0x555555cdcb70) at /var/tmp/portage/media-video/qmplay2-9999/work/qmplay2-9999/src/qmplay2/vulkan/VulkanWindow.cpp:952
#9  0x00007ffff7db8f4c in QmVk::Window::render (this=0x555555cdcb70) at /var/tmp/portage/media-video/qmplay2-9999/work/qmplay2-9999/src/qmplay2/vulkan/VulkanWindow.cpp:527
#10 0x00007ffff7dc2468 in QmVk::Window::event (this=0x555555cdcb70, e=0x7fffffffc1a0) at /var/tmp/portage/media-video/qmplay2-9999/work/qmplay2-9999/src/qmplay2/vulkan/VulkanWindow.cpp:1548
#11 0x00007ffff60f2ff4 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt6Widgets.so.6
#12 0x00007ffff60f3ecc in QApplication::notify(QObject*, QEvent*) () at /usr/lib64/libQt6Widgets.so.6
#13 0x00007ffff5116ef3 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib64/libQt6Core.so.6
#14 0x00007ffff576fb2e in QPlatformWindow::deliverUpdateRequest() () at /usr/lib64/libQt6Gui.so.6
#15 0x00007fffeadd0fc1 in QtWaylandClient::QWaylandWindow::deliverUpdateRequest() () at /usr/lib64/qt6/plugins/platforms/../../../libQt6WaylandClient.so.6
#16 0x00007ffff515de35 in QObject::event(QEvent*) () at /usr/lib64/libQt6Core.so.6
#17 0x00007ffff60f2ff4 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt6Widgets.so.6
#18 0x00007ffff60f3ecc in QApplication::notify(QObject*, QEvent*) () at /usr/lib64/libQt6Widgets.so.6
#19 0x00007ffff5116ef3 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib64/libQt6Core.so.6
#20 0x00007ffff5117f8c in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib64/libQt6Core.so.6
#21 0x00007ffff53960e3 in ??? () at /usr/lib64/libQt6Core.so.6
#22 0x00007ffff2703602 in ??? () at /usr/lib64/libglib-2.0.so.0
#23 0x00007ffff2770588 in ??? () at /usr/lib64/libglib-2.0.so.0
#24 0x00007ffff27028ac in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#25 0x00007ffff5395b30 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt6Core.so.6
#26 0x00007ffff5120716 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt6Core.so.6
#27 0x00007ffff5117604 in QCoreApplication::exec() () at /usr/lib64/libQt6Core.so.6
#28 0x00005555555d6e9b in main (argc=2, argv=0x7fffffffd558) at /var/tmp/portage/media-video/qmplay2-9999/work/qmplay2-9999/src/gui/Main.cpp:921
```

**Comment by FireBurn** [comment]
D'oh simply going to full screen exhibits the same behavior

**Comment by FireBurn** [comment]
Thanks, this has been fixed in Mesa
